name: xwayland-kiosk-helper
version: 2
summary: Helper to run X11 apps on a Wayland kiosk
description: |
  Helper to run X11 applications on a Wayland kiosk, using Xwayland
  and a basic window manager to enforce fullscreen kiosk behaviour.
  .
  Can works in collaboration with the snapcraft desktop helpers:
  https://github.com/ubuntu/snapcraft-desktop-helpers
  .
  Usage:
    1. add "after: [desktop-<technology>, xwayland-kiosk-helper]" to your
       launcher (selecting the correct toolkit technology)
    2. prepend your command with "desktop-launch xwayland-kiosk-launch", like:
         command: "desktop-launch xwayland-kiosk-launch $SNAP/path/to/foo"
    3. configure the internal i3 window manager to fullscreen your X11 apps.
       Do this by setting one of the following variables in the YAML:

         a. XWAYLAND_FULLSCREEN_WINDOW_HINT to give i3 a specifier for the window to
            make fullscreen. Some specifiers are:
              - class="Firefox"
              - window_role="browser-window"
              - title="Mozilla Firefox"
            See https://i3wm.org/docs/userguide.html#command_criteria for all specifiers.
            A suitable i3.config file with this hint will be created and used.

            Example usage:
              command: something
              environment:
                XWAYLAND_FULLSCREEN_WINDOW_HINT: 'window_role="browser-window"'

         b. XWAYLAND_I3_CONFIG_FILE to the in-snap path of your own i3 config file.

            Example:
              command: something
              environment:
                XWAYLAND_I3_CONFIG_FILE: $SNAP_DATA/i3.config

            See https://i3wm.org/docs/userguide.html#configuring on syntax for i3.config
            Don't forget to install the file in the snap.

    4. for full confinement need to add these plugs and slots
       slots: [ x11 ]
       plugs: [ x11-plug, opengl, wayland ]
      
       plugs:
         x11-plug: # because cannot have identical plug/slot name in same yaml.
           interface: x11

confinement: strict

parts:
  xwayland-kiosk-helper:
    plugin: cmake
    source: xwayland-preload
    build-packages:
      - build-essential
    stage-packages:
      - xwayland
      - i3
      - libegl1-mesa
      - libgl1-mesa-glx
#    prime:
#      - bin/xwayland-kiosk-launch
#      - lib/libxwayland-preload.so
#      - usr/bin/Xwayland
#      - usr/bin/xkbcomp
#      - usr/bin/i3
#      - usr/lib/xorg/*
#      - usr/lib/*/lib*
#      - -usr/lib/*/libperl*
#      - usr/lib/*/dri
#      - usr/lib/*/mesa
#      - usr/lib/*/mesa-egl
#      - usr/share/fonts
#      - usr/share/libdrm
#      - usr/share/glib-2.0
#      - usr/share/X11
#      - etc/drirc
#      - etc/fonts
#      - etc/i3
#      - etc/X11
      

